### PR TITLE
Cl timestamp

### PR DESCRIPTION
**Pull request by yubocheng**
Add time stamps to collectl output and functions for plotting

### CODE REVIEW

**Comment by vjcitn** [comment]
Hi, I am trying to run the vignette on a large machine -- I found that the image for each core got to 5GB.  As it works on MNN, the RAM consumption is up to 50GB.  I wonder if we should put some commentary in the workflow.Rmd vignette that warns the user about consumption and gives advice on choosing a platform and configuring.

**Comment by vjcitn** [comment]
@yubocheng do you have a copy of the compiled workflow.Rmd that you can share?

**Comment by vjcitn** [comment]
@yubocheng would you also add some guard rails to the DESCRIPTION giving minimal version of R required, and minimal versions of other packages used -- like hca.  Thanks, this is really a nice example.

**Comment by vjcitn** [comment]
One more thing -- today I used "sudo apt-get install -y collectl" on an ubuntu system.  Running the vignette to the end necessitated using n_to_skip = 15 for the cl_parse calls.  Can you check this?

**Comment by vjcitn** [comment]
```
stvjc@rex3:~/Rcollectl/vignettes$ collectl --version
collectl V4.3.1-1 (zlib:2.084,HiRes:1.976)

Copyright 2003-2018 Hewlett-Packard Development Company, L.P.
collectl may be copied only under the terms of either the Artistic License
or the GNU General Public License, which may be found in the source kit
```

**Comment by vjcitn** [comment]
I think we should be very explicit in SystemRequirements on what we are expecting to use.

**Comment by yubocheng** [comment]
@vjcitn The workflow of hca dataset needs 60 GB memory and 16 CPUs. Dose it make more sense to move workflow.Rmd to a separate project and only keep function cl_timestamp in Rcollectl?

**Comment by vjcitn** [comment]
Hi @yubocheng I think that is right.  We should make a Bioconductor "workflow" document that has the large requirements, and just add the timestamp and instructions on how to use it, in the Rcollectl.  Thank you!

**Comment by yubocheng** [comment]
Hi @vjcitn Workflow.Rmd is removed, and only function cl_timestamp is added to Rcollectl. Thanks

**Comment by yubocheng** [comment]
Hi Vince,

Please see attached compiled vignette, and workflow.Rmd is updated at https://github.com/yubocheng/Rcollectl/tree/cl_timestamp/vignettes. I'm still working on adding parameters to the vignette (fileid and sample), as well as putting it on docker. Will talk to Martin about advice on choosing a platform and configuring. Thanks
________________________________
From: Vince Carey ***@***.***>
Sent: Wednesday, August 17, 2022 4:32 PM
To: vjcitn/Rcollectl ***@***.***>
Cc: Cheng, Yubo ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL: Re: [vjcitn/Rcollectl] Cl timestamp (PR #1)


@yubocheng<https://secure-web.cisco.com/1lH9Tt86Jgfy9ryml6TXhQjJAJRiBA7jpOkXOKqd30fOXqhl-p1ENZ0cx6MxOocVO2H-CcpLvQjB2yvjZksADcoU-QvUlSdzrRr-5vHauwMmf32ddMlRntfftuZt-0IGmZvSKGADmc5GQI0VRpisvAuRuR-veI6bSYWAaIN1Eg5zdpb-e5Aqwrd74chU8kj5uNrn9a3qOBkmLiDt3C35l6R_Da1PKzwEvQo4EYVSS9Jw3bZNCvAgn3Tf9M9mEIwXBs9cxISXQ9Cb2p7i4H3bPIyDoxNZIT-VK6ops1QFk1JPrwE98uO8lr8fV8pqBWQd1/https%3A%2F%2Fgithub.com%2Fyubocheng> would you also add some guard rails to the DESCRIPTION giving minimal version of R required, and minimal versions of other packages used -- like hca. Thanks, this is really a nice example.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/19bbybAwcUK62Ye05xoiPo8KtUFlOszNx9OH6wt6HnTF-VK0WFKzqSaRZioSIzEoZE7h3DphNKDW-KNAXrinzC89_TW6itKMax0fH9G4UGArWBfRWMzT_c7aQvxMOLxD9A_AnXQOgx67T7rlqzvvAC1t7pw_5v75rJxPVndrLOIXaql0bwS9hMRc-5CgOgQ5KvxhqJdErtjmkIi2FN61gn_BNnvRwRbnpqo3C_KLatzVzFS_CkZ5wsloeAgKk3HjS8rDUqErJ7wLW81B4HONNDdvHR2Yg5N2ZVYXE3g6rQNhF-BgyJPQGgpGbGg6z5wzC/https%3A%2F%2Fgithub.com%2Fvjcitn%2FRcollectl%2Fpull%2F1%23issuecomment-1218462987>, or unsubscribe<https://secure-web.cisco.com/1nSEBqsbhZiArTjWFLMLyE2ai1JKutcn75hXHnYvMxUrR0xj9ZPOrSSQLmWDeFFM36XTH18oxpVZAIaMqI7QawBccCVFK-U5Ur3uFztK_GqsZhtyXu4CH6yvDLHO-CuqaEB9J6lJ6a0wx7ez7YbPDysYNr1rOZAnxX56PqXZSIZ7r7wRnGV-Svfw33eLpg1yzITDTv0vdWL0-Sa0stdUnhGwt_vDWod82QXmhy6Ka9XtEodQZLuXiqAnubytCw5xsjccuGJAtaa-EVba-GYnL8HiD7LCvJNmnbqyl0uoNTd-SggimzXOgjNeOejVeh0Ne/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAECDIFHNP3PGNJRYXAN7DNDVZVD6FANCNFSM54E3RSLA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


This email message may contain legally privileged and/or confidential information.  If you are not the intended recipient(s), or the employee or agent responsible for the delivery of this message to the intended recipient(s), you are hereby notified that any disclosure, copying, distribution, or use of this email message is prohibited.  If you have received this message in error, please notify the sender immediately by e-mail and delete this email message from your computer. Thank you.

**Comment by vjcitn** [comment]
Hi @yubocheng  ... I merged the pull request, but there was no attachment to the email, so I have not seen
the compiled workflow.  Thanks!

**Comment by yubocheng** [comment]
Hi @vjcitn Thank you very much! The vignette of workflow (both Rmd and compiled) was moved to another project https://github.com/yubocheng/Rcollectlworkflow to keep Rcollectl clean. Thanks

**Pull request merged**
